name: status_saver_bloc
description: A Status Saver App
publish_to: 'Play Store'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.2
  go_router: ^10.0.0
  google_fonts: ^4.0.4
  meta: ^1.9.1
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  shared_preferences: ^2.2.0
  gallery_saver: ^2.3.2
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3
  share: ^2.0.4
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  local_auth: ^2.1.7
  local_auth_android: ^1.0.36

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/Assets/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/
